### ISSUE TITLE
'UNKNOWN()'

### ISSUE THREAD

**Issue by Monteo** [shirsig/npcscan#10]
1x [ADDON_ACTION_FORBIDDEN] Модификация 'unitscan' пыталась вызвать защищенную функцию 'UNKNOWN()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: ?
[C]: in function `TargetUnit'
unitscan\unitscan.lua:49: in function `target'
unitscan\unitscan.lua:39: in function `check_for_targets'
unitscan\unitscan.lua:311: in function `UPDATE'
unitscan\unitscan.lua:2: in function <unitscan\unitscan.lua:2>

**Comment by shirsig** [comment]
That's intended. This error is how it detects units. The function only throws the error when the unit was there. Afaik the only way to do it in classic.
