### ISSUE TITLE
Can unitscan exclude dead mobs?

### ISSUE THREAD

**Issue by robmonte** [shirsig/npcscan#11]
I know with macros you can have a [nodead] modifier to exclude dead enemies. Is unitscan capable of doing either using this or making it an optional feature? I can see some situations where you'd want it to find dead enemies but many times you only want living targets.

**Comment by shirsig** [comment]
No, it's not possible.

**Comment by robmonte** [comment]
@shirsig Is this feature now possible in TBC?

**Comment by shirsig** [comment]
Still not possible, sorry.
