### ISSUE TITLE
error: attempted to call a forbidden function (TargetUnit())

### ISSUE THREAD

**Issue by Djfe** [shirsig/npcscan#15]
First of all, huge thank you for porting/developing and maintaing this add-on :)

I just tested this out (first time) with Lucifron and while it works (triggers), I get a lua error from WoW:
```
Date: 2020-04-02 19:32:59
ID: 1
Error occured in: AddOn: unitscan
Count: 103
Message: Error: AddOn unitscan attempted to call a forbidden function (TargetUnit()) from a tainted execution path.
Debug:
   [C]: TargetUnit()
   unitscan\unitscan.lua:42: target()
   unitscan\unitscan.lua:272: UPDATE()
   unitscan\unitscan.lua:3:
      unitscan\unitscan.lua:3
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  aPVPName1s2s, v1.31
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.3.4
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.7
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GTFO, v4.55
  HonorAssist, v0.9.4
  Informant, v8.2.6374 (SwimmingSeadragon)
  InstanceCounter, v1.13.3.3
  NovaWorldBuffs, v1.29
  oRA3, vv4-classic
  Questie, v5.10.0 0 fd3ff918
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TradeSkillMaster, vv4.9.32
  TradeSkillMasterAppHelper, vv4.0.8
  unitscan, v1.0.0
  WeakAuras, v2.16.6
  BlizRuntimeLib_deDE v1.13.4.11304 <none>
  (ck=5ab)
```
someone on Twitch in the comments of this add-on mentions something similar and says, that this error started appearing after the latest major WoW classic patch

Or is this bug related to the last update from March 11?

**Comment by shirsig** [comment]
This error has to happen because it is actually how the units are detected (in classic). However, the error doesn't necessarily have to be shown. I've made it so that the default UI doesn't show it, but I cannot prevent other addons from showing it. If it suddenly started appearing I assume you started using some new UI addon.

**Comment by Djfe** [comment]
I see
I had ElvUI installed for a couple of days (might be the culprite)

Do I have to test this with a clean config or should deactivating all other add-ons be enough? (afaik ElvUI configures a lot of stuff over vanilla variables, suddenly all chat tabs (their settings) are synced over my account and not based on my pc, since I used it)

**Comment by Djfe** [comment]
Ah I found out which add-on: it's swatter
https://legacy-wow.com/tbc-addons/swatter/

I have swatter because I installed auctioneer (enchantrix would've been enough for me)
