### ISSUE TITLE
[Not an issue] This should be included...

### ISSUE THREAD

**Issue by Seminko** [shirsig/npcscan#2]
Hey, not sure why but noticed that the addon doesn't come with any rares "pre-packed"... so I did it myself. Feel free to include that in the addon. And feel free to mention me ;)
[npcscan.txt](https://github.com/shirsig/npcscan/files/1414723/npcscan.txt)

**Comment by jackajack** [comment]
Thanks mate I'm using this, do you have same kind of problems as I do here? https://github.com/shirsig/npcscan/issues/3

**Comment by shirsig** [comment]
Does not work well with scanning in vanilla.

**Comment by Seminko** [comment]
What do you mean it does not work well? Well what I found out is that the names need to be in all caps for some reason, otherwise it won't work, but if they are the list works like a charm.

Also, would be great if every session the list would get updated again (if selected in the settings).

**Comment by shirsig** [comment]
Look at the other issue linked byjackjack

**Comment by Seminko** [comment]
It did that when I used the list as is. When I use the list in all caps, it works properly. No constant targetting, proper sound and popup alert...

**Comment by shirsig** [comment]
I just assumed from the bug that you had a permanent list. The limitation inherent to this scanning is that the name has to be removed from the list once it's detected.

I think it would be useful to be able to manage the names in an easier way, like having a gui listing where they don't get removed but deactivated and you can reactivate them or something, maybe I'll do that sometime, but making a gui is always a bother. It would be nice to not have to retype something all the time that you're camping.

In a rare list I don't see much of a point in vanilla as only nazjak and two hunter pets are interesting, the rest would just be annoying, and the addon doesn't just scan for rares anyway. I mostly use it for players/questmobs.

There's further another issue that the addon cannot tell apart npcs from players/pets before targeting them so if you have a list with many names you'll constantly get something like an alert for a pet named "lupos".

Finally it will also impact performance if you have a long list.
