### ISSUE TITLE
[Request] Alert window position control options

### ISSUE THREAD

**Issue by Slivo-fr** [shirsig/npcscan#21]
First thanks for this useful port and your work.

Then, I could really use a way to move the alert window position on the screen (A per character setting would be wonderful)

**Comment by shirsig** [comment]
I think you can move it when holding down control, or maybe it was alt.

**Comment by Slivo-fr** [comment]
Holy crap, thanks ! It's ctrl + drag
It could be a good idea to add this to the project description :D

Thanks for your quick answer ❤️
