### ISSUE TITLE
Constantly Targets A Rare

### ISSUE THREAD

**Issue by jackajack** [shirsig/npcscan#3]
I'm using it with Luna Unit Frames and
1- When a rare is around(I use the rare list the other guy shared here), my client constantly targets it even if I try to change target. Nothing works except logging out and disabling npcscan.
2- I don't know why but I don't get the "flashy" alert on mob find. It just targets the rare (and sticks to it).

**Comment by shirsig** [comment]
That's why it doesn't include a rare list :) (besides all but 3 vanilla rares being completely worthless) The only way to scan in vanilla is with the targeting api

**Comment by jackajack** [comment]
So is it normal for npcscan to target npcs constantly? It doesn't let me un-target.
Also no flashy alert is strange isn't it?

Btw which 3 rares are important?

**Comment by shirsig** [comment]
Unmodified npcscan will remove a name from the scan list as soob as it detects it to avoid this issue. Then you have to add it back if you want to scan for it again.

**Comment by jackajack** [comment]
Let's say you add this manually to savedvariables:
npcscan_targets = {
	["7:XT"] = true,
}

Does that mean npcscan can't remove 7:XT from the list when found?
It feels like it should work the same as /npcscan 7:XT command ingame.

Also please tell 3 important rares because I really want to know.

**Comment by shirsig** [comment]
No, that should work. But like i said, kinda pointless anyway as only prince nazjak and lupus/broken tooth for hunters are interest8ng. I used it more often for camping questmobs and detecting gankers actually. Will probably also rename it to unitscan at some point.

**Comment by shirsig** [comment]
Having lots of names on the list will also cauze performance issues

**Comment by jackajack** [comment]
Still it's cool to know you're not missing any rares you pass by. The list has around 200-250 rare names. I didn't notice any performance issues.

My issues are:
1- Constant targeting
2- No flashy alert

Do you have any idea why?
