### ISSUE TITLE
Final Stress Test

### ISSUE THREAD

**Issue by Peetytwist** [shirsig/npcscan#5]
Hey,
I get this message while using it in the final stress test of WoW Classic today:

Message: Interface\AddOns\unitscan\unitscan.lua:27: attempt to call a table value
Time: Fri Aug  9 16:02:56 2019
Count: 726
Stack: Interface\AddOns\unitscan\unitscan.lua:27: attempt to call a table value
Interface\AddOns\unitscan\unitscan.lua:27: in function `check_for_targets'
Interface\AddOns\unitscan\unitscan.lua:299: in function `UPDATE'
Interface\AddOns\unitscan\unitscan.lua:2: in function <Interface\AddOns\unitscan\unitscan.lua:2>

Locals: (for generator) = <table> {
}
(for state) = nil
(for control) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call a table value"
unitscan = <unnamed> {
 0 = <userdata>
 UPDATE = <function> defined @Interface\AddOns\unitscan\unitscan.lua:296
 print = <function> defined @Interface\AddOns\unitscan\unitscan.lua:304
 toggle_target = <function> defined @Interface\AddOns\unitscan\unitscan.lua:319
 button = unitscan_button {
 }
 flash = <unnamed> {
 }
 sorted_targets = <function> defined @Interface\AddOns\unitscan\unitscan.lua:310
 LOAD = <function> defined @Interface\AddOns\unitscan\unitscan.lua:50
 target = <function> defined @Interface\AddOns\unitscan\unitscan.lua:40
 last_check = 318517.982000
 play_sound = <function> defined @Interface\AddOns\unitscan\unitscan.lua:15
 check_for_targets = <function> defined @Interface\AddOns\unitscan\unitscan.lua:26
}

**Comment by shirsig** [comment]
Hey. This is not one of the addons I'm trying to port (https://old.reddit.com/r/classicwow/comments/bxf1lc/aux_auction_house_addon_experimental_classic/).
It seems they disallowed addons from auto targeting so its mechanism of detection doesn't work. Perhaps one of the later npcscans might be portable but I'll leave that to their developers.
