### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by astateofmind01** [shirsig/npcscan#8]
When i copy the code in a folder names npcscan it doesn't appear in the list of loaded addons.
If i rename the folder to unitscan it appears but it doesn't work - doesn't select the npc although i'm right by it and i use /unit scan npc_name

**Comment by shirsig** [comment]
Only the **retail** branch is supposed to work in classic and only with a lot of limitations due to the API changes. Also, the command is /unitscan without spaces.
