### ISSUE TITLE
Request - A flag to permanently add a name to the scan list

### ISSUE THREAD

**Issue by robmonte** [shirsig/npcscan#9]
It would be nice to have another command like 
`/unitscan perm [name]`
so that it doesn't get removed upon success, unless I purposefully run the command again to remove it.

**Comment by shirsig** [comment]
Removing the target wasn't a feature but a necessity in 1.12.
In classic it is actually not needed so in the newest version the targets are never automatically removed anymore.

**Comment by robmonte** [comment]
Thanks!
